### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hithto** [dmaria58/react_demo#2]
router.post('/upload',async function (ctx, next) {})
                      ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)

**Comment by dmaria58** [comment]
bug已经修复，已删除不用的路由，上传的功能还没有做，感谢反馈问题。
